language: python
matrix:
  include:
   - env: TOXENV=py27-dj18
     python: 2.7
   - env: TOXENV=py34-dj18
     python: 3.4
   - env: TOXENV=py35-dj18
     python: 3.5
   - env: TOXENV=py27-dj110
     python: 2.7
   - env: TOXENV=py34-dj110
     python: 3.4
   - env: TOXENV=py35-dj110
     python: 3.5
   - env: TOXENV=py27-dj111
     python: 2.7
   - env: TOXENV=py34-dj111
     python: 3.4
   - env: TOXENV=py35-dj111
     python: 3.5
   - env: TOXENV=py36-dj111
     python: 3.6
install:
  - pip install coverage codecov coveralls tox
script:
  - ./bin/fake-server &
  - tox
after_success:
  - coveralls
  - codecov
