language: python
install:
  - pip install coverage codecov coveralls tox
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
script:
  - ./bin/fake-server &
  - tox
after_success:
  - coveralls
  - codecov
env:
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py27-django19

  - TOXENV=pypy-django17
  - TOXENV=pypy-django18
  - TOXENV=pypy-django19

  - TOXENV=py33-django17
  - TOXENV=py33-django18

  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django19

  - TOXENV=py35-django18
  - TOXENV=py35-django19
