language: python
matrix:
  include:
  - env: TOXENV=py27-dj19
    python: 2.7
  - env: TOXENV=py34-dj19
    python: 3.4
  - env: TOXENV=py35-dj19
    python: 3.5
  - env: TOXENV=py27-dj110
    python: 2.7
  - env: TOXENV=py34-dj110
    python: 3.4
  - env: TOXENV=py35-dj110
    python: 3.5
  - env: TOXENV=py27-dj111
    python: 2.7
  - env: TOXENV=py34-dj111
    python: 3.4
  - env: TOXENV=py35-dj111
    python: 3.5
  - env: TOXENV=py36-dj111
    python: 3.6
  - env: TOXENV=py34-dj20
    python: 3.4
  - env: TOXENV=py35-dj20
    python: 3.5
  - env: TOXENV=py36-dj20
    python: 3.6
install:
- pip install coverage codecov coveralls tox
script:
- "./bin/fake-server &"
- tox
after_success:
- coveralls
- codecov
deploy:
  provider: pypi
  user: apsl
  password:
    secure: NONnSh3dzxHTBj4cO3cxcqXVrYXZRhxYk/yMWxKbJs8FEfkoeof2xdOQybgH27tim5rrqPHUbpgJsYeV8QHMdSPcWHIjxJujOy+/Ks0DukqJx1fm79Bly2NDKLxMw5DB+9cUllm94Zj9CNye034KxwcDPB0vsJUjBKHNHhGeGQkfM2/vVvcJxOYs43hvE2OAUoR+8kPkg2SZVuxgD/g5hS8YWNbEl1a2S7hk/N0BkDgJvI73wVj6Sl3wHWFHhOzpXM28md//BPz7kHNGFHtsoiq7JLsw/IOgTOrR4S1f90J/GOLd4otN0DkOOFJbpdEvsKbGRxi8Yf31zOYd/Qo+1nQ5j9WX4ZtEsKV0sDQ61KhMmcWjFlq/LMpbo6dok385TNRg+J8fFHt6BezrJYvEspzTvkcQzrOhCdGfdgqa1YhtNJeRB/AvrFHWOLafYFlwya+aa4no+x7OLkP6DcOfIB4NYodSMAorW3Zd4JRGz4W8Cm/t+azt94aTk/sD0+F2+OZGDM/qjk1/N9zpoHW04ubabYU2fWSJsIFA4j5LB71N1jgx/lxHxYQujdqSMYkLV2uNwWXAJWXJBHxGdCGbryAsSJ8dqL2J2ifWmY42geXtJKO46uZh7wIe9yUR/PWd4EhCd87z0zhu7heWyrkJFrS1kwty03lfO0e8J0RSnGA=
  on:
    tags: true
    branch: master
  distributions: sdist bdist_wheel
