language: python
install:
  - pip install coverage codecov coveralls tox django-rq
services:
  - redis-server
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
script:
  - ./bin/fake-server &
  - tox
after_success:
  - coveralls
  - codecov
env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110

  - TOXENV=py33-django18

  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110

  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
