# Generated by Django 2.2.11 on 2020-03-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_yubin', '0006_auto_20200319_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (1, 'queued'), (2, 'in process'), (3, 'sent'), (4, 'failed'), (5, 'blacklisted'), (6, 'discarded')], default=0, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='log',
            name='log_message',
            field=models.TextField(blank=True, verbose_name='log'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (1, 'queued'), (2, 'in process'), (3, 'sent'), (4, 'failed'), (5, 'blacklisted'), (6, 'discarded')], default=0),
        ),
    ]
