# Generated by Django 3.1.3 on 2020-11-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_yubin', '0009_auto_20200320_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_enqueued',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date enqueued'),
        ),
        migrations.AddField(
            model_name='message',
            name='enqueued_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Times the message has been enqueued', verbose_name='enqueued count'),
        ),
    ]
