# Generated by Django 3.2.16 on 2022-11-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_yubin', '0009_auto_20221102_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='_encoded_message',
            new_name='_message_data',
        ),
        migrations.AlterField(
            model_name='message',
            name='_message_data',
            field=models.TextField(db_column='encoded_message', verbose_name='message data'),
        ),
    ]
