# Generated by Django 3.2.16 on 2022-11-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_yubin', '0010_auto_20221115_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='_message_data',
            field=models.TextField(db_column='message_data', verbose_name='message data'),
        ),
    ]
