services:

  postgres:
    image: postgres:14.3-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres:/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=yubin
      - POSTGRES_USER=yubin
      - POSTGRES_DB=yubin

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  mail:
    image: python:3.10-alpine
    init: true  # https://stackoverflow.com/a/62854251/6677560
    command: 'python -m smtpd -n -c DebuggingServer 0.0.0.0:1025'
    ports:
      - "1025:1025"

  minio:
    image: minio/minio:RELEASE.2022-10-29T06-21-33Z
    command: 'server /data --console-address ":9001"'
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_SERVER_HOST=minio
      - MINIO_ROOT_USER=yubin
      - MINIO_ROOT_PASSWORD=yubinyubin

  create_bucket:
    # Create the bucket: $ docker compose run --rm create_bucket
    image: minio/mc:RELEASE.2022-10-29T10-09-23Z
    profiles:
      - setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 yubin yubinyubin;
      mc mb --ignore-existing myminio/yubin;
      exit 0;
      "
